// Generated by npm run content:bupha — do not edit by hand.
// Edit src/content/case-studies/bupha.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const buphaCaseStudy = {
  "kind": "minor",
  "slug": "bupha",
  "hero": {
    "breadcrumb": "Bupha",
    "eyebrow": "010 · Graphic Design · Illustration",
    "titleLine1": "Bupha",
    "titleLine2": "Line",
    "summary": "Graphic design and illustration for a local business's friendlier sub-brand, a separate product line that invites approachability without abandoning the parent shop's credibility.",
    "layout": "split",
    "image": {
      "src": "/projects/bupha/bupha-cover.png",
      "alt": "Bupha cover image"
    },
    "meta": [
      {
        "label": "Client",
        "value": "Local business · Thailand"
      },
      {
        "label": "Role",
        "value": "Graphic design + illustration"
      },
      {
        "label": "Timeline",
        "value": "3 weeks"
      },
      {
        "label": "Deliverable",
        "value": "Label system + illustration set"
      }
    ]
  },
  "approachLabel": "The Decision",
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "Friendly enough",
      "titleEm": "to try.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "An established local business wanted a secondary product line aimed at younger customers and gift buyers, same quality, warmer personality. The parent brand reads formal. Bupha needed to feel approachable from three metres on a market stall.",
            "Scope covered label graphics, a small illustration set for three products, and a simple brand mark extension, not a full rebrand."
          ]
        },
        {
          "type": "stats",
          "items": [
            {
              "value": "3",
              "label": "Product labels",
              "variant": "dark"
            },
            {
              "value": "6",
              "label": "Illustration motifs",
              "variant": "mid"
            },
            {
              "value": "3",
              "label": "Week sprint",
              "variant": "light"
            }
          ]
        }
      ]
    },
    "approach": {
      "eyebrow": "02 · The Decision",
      "title": "Hand-drawn over",
      "titleEm": "geometric clean.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Geometric minimalism matched the parent brand too closely. Bupha would have disappeared. Loose hand-drawn illustration with rounded type won stall-side tests: warmer, more giftable, still legible at small label size."
          ]
        },
        {
          "type": "callout",
          "label": "Tradeoff",
          "title": "Warmth vs. clutter",
          "body": "Illustration density capped at one hero motif per label, charm without losing product name and price at a glance."
        }
      ]
    },
    "work": {
      "eyebrow": "03 · Work",
      "title": "Labels and",
      "titleEm": "motif library.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Six illustration motifs, ingredients, local landmarks, gift moments, mix across three product labels. Shared border treatment and rounded sans type unify the line without repeating the same hero image."
          ]
        },
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Illustration set",
              "body": "Hand-drawn motifs digitised with consistent line weight and two-colour palette."
            },
            {
              "num": "02",
              "title": "Label grid",
              "body": "Product name, illustration panel, and legal copy zones locked for three SKUs."
            },
            {
              "num": "03",
              "title": "Stall mock",
              "body": "Labels tested on product jars at arm's length, readability pass before print."
            }
          ]
        }
      ]
    },
    "outcome": {
      "eyebrow": "04 · Outcome",
      "title": "Giftable",
      "titleEm": "sub-brand.",
      "blocks": [
        {
          "type": "outcomes",
          "items": [
            {
              "value": "3",
              "label": "Product labels",
              "body": "Print-ready label artwork for three SKUs with shared system and unique motifs."
            },
            {
              "value": "✓",
              "label": "Client launch",
              "body": "Bupha line debuted at a weekend market. Illustration style cited as top purchase driver in informal feedback."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "A small-scope project that proved how much personality illustration adds when the parent brand can't flex. Bupha feels like a welcome, not a compromise."
          ]
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default buphaCaseStudy;
