// Generated by npm run content:busaba — do not edit by hand.
// Edit src/content/case-studies/busaba.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const busabaCaseStudy = {
  "kind": "minor",
  "slug": "busaba",
  "hero": {
    "breadcrumb": "Signature Dessert & Fork",
    "eyebrow": "001 · Industrial Design · Signature dessert + bespoke fork",
    "titleLine1": "Signature Dessert",
    "titleLine2": "& Fork",
    "summary": "A signature plated dessert and a bespoke fork for a fine dessert bar in Ayutthaya, each form translated from a piece of local heritage.",
    "image": {
      "src": "/projects/busaba/busaba-cover.png",
      "alt": "Signature dessert and bespoke fork styled together on a plate"
    },
    "meta": [
      {
        "label": "Client",
        "value": "Fine dessert bar, Ayutthaya, Thailand"
      },
      {
        "label": "Role",
        "value": "Industrial design, form development, prototyping"
      },
      {
        "label": "Timeline",
        "value": "2021"
      },
      {
        "label": "Deliverable",
        "value": "Signature dessert form + bespoke fork"
      }
    ]
  },
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "Heritage to",
      "titleEm": "the table.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/busaba/busaba-architecture.jpeg",
          "alt": "Busaba signature architecture scene",
          "caption": "Busaba signature white Thai architecture hotel.",
          "size": "md"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  Busaba, the hotel and cafe provider in Ayutthaya wanted a signature dessert and its own presentation in their new fine dessert bar, objects that felt native to where they stood, not generic fine-dining props."
          ]
        },
        {
          "type": "pullquote",
          "text": "Both had to survive real service.",
          "source": "The constraint"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  The dessert had to be repeatable by the kitchen, the fork producible and comfortable in the hand. Success meant two objects a guest would recognise as belonging only to this place."
          ]
        }
      ]
    },
    "work": {
      "eyebrow": "02 · Work",
      "title": "Heritage, translated",
      "titleEm": "into form.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "  I worked from two fixed sources as a reference, one per object. The design decision that held the piece together was pairing them, brand heritage in the tool, civic heritage on the plate, so the two objects read as a matched set rather than a dessert with cutlery beside it."
          ]
        },
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Source",
              "body": "Client's traditional Thai architecture; Ayutthaya's historic coinage."
            },
            {
              "num": "02",
              "title": "Translate",
              "body": "Reducing each source to a silhouette that holds as edible form and as cutlery."
            },
            {
              "num": "03",
              "title": "Produce",
              "body": "Prototyping the fork for the hand; setting the dessert form for repeatable service."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "  The fork's form is drawn from the client's own iconic traditional Thai architecture, extracting a curve and line, applied into the cutlery form."
          ]
        },
        {
          "type": "image",
          "src": "/projects/busaba/busaba-fork-ref.png",
          "alt": "Busaba signature architecture scene lines",
          "caption": "Busaba signature white Thai architecture hotel and its extracted line and form."
        },
        {
          "type": "image",
          "src": "/projects/busaba/busaba-fork-design.png",
          "alt": "Busaba signature architecture scene",
          "caption": "3D render and applied line and form to the fork design"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  Meanwhile, the dessert's \"Thong-Bolan\" silhouette is from Ayutthaya's old currency called \"Pod-Duang\", minimised the shape and details, while still be able to keep the form of the currency."
          ]
        },
        {
          "type": "imagePair",
          "items": [
            {
              "src": "/projects/busaba/busaba-podduand-ref.png",
              "alt": "Left",
              "caption": "Pod-Duang currency"
            },
            {
              "src": "/projects/busaba/busaba-podduand-design.png",
              "alt": "Right",
              "caption": "3D render Thong-Bolan design following Pod-Duang shape and form"
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "  Each source was reduced to a single clean silhouette that had to survive translation into a very different material: one edible and repeatable, one metal and ergonomic."
          ]
        },
        {
          "type": "imagePair",
          "items": [
            {
              "src": "/projects/busaba/busaba-fork-use.png",
              "alt": "Real fork usage photo from customer",
              "caption": "In service fork photo from customer"
            },
            {
              "src": "/projects/busaba/busaba-thongboran.png",
              "alt": "Left",
              "caption": "Real housemade Thong-Bolan photo from customer"
            }
          ]
        }
      ]
    },
    "outcome": {
      "eyebrow": "03 · Outcome",
      "title": "The result",
      "titleEm": "on the plate.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/busaba/busaba-final.png",
          "alt": "Busaba signature architecture scene",
          "caption": "Live Busaba dessert bar"
        },
        {
          "type": "outcomes",
          "items": [
            {
              "value": "2 sources",
              "label": "Heritage languages translated",
              "body": "Client architecture and civic currency rendered into two matched objects."
            },
            {
              "value": "In service",
              "label": "Signature tableware",
              "body": "Both dessert and fork served as the bar's signature pairing after opening."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "Translating fixed heritage, architecture, Ayutthaya's currency, into new physical objects is the same move I make now, turning brand and context into a digital product interface."
          ]
        },
        {
          "type": "button",
          "label": "Visit the Customer",
          "href": "https://www.facebook.com/DessertBarBusaba/?locale=th_TH",
          "variant": "accent"
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default busabaCaseStudy;
