// Generated by npm run content:busaba — do not edit by hand.
// Edit src/content/case-studies/busaba.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const busabaCaseStudy = {
  "kind": "minor",
  "slug": "busaba",
  "hero": {
    "breadcrumb": "Signature Dessert & Fork",
    "eyebrow": "001 · Industrial Design · Signature dessert + bespoke fork",
    "titleLine1": "Signature Dessert",
    "titleLine2": "& Fork",
    "summary": "A signature plated dessert and a bespoke fork for a fine dessert bar in Korat, each form translated from a piece of local heritage.",
    "image": {
      "src": "/projects/signature-dessert-fork/cover.png",
      "alt": "Signature dessert and bespoke fork styled together on a plate"
    },
    "meta": [
      {
        "label": "Client",
        "value": "Fine dessert bar, Korat, Thailand"
      },
      {
        "label": "Role",
        "value": "Industrial design, form development, prototyping"
      },
      {
        "label": "Timeline",
        "value": "2021"
      },
      {
        "label": "Deliverable",
        "value": "Signature dessert form + bespoke fork"
      }
    ]
  },
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "One place, two",
      "titleEm": "objects.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "A fine dessert bar opening in Korat wanted a signature dessert and its own fork, objects that felt native to where it stood, not generic fine-dining props. The constraint: both had to survive real service. The dessert had to be repeatable by the kitchen, the fork producible and comfortable in the hand. Success meant two objects a guest would recognise as belonging only to this place."
          ]
        }
      ]
    },
    "work": {
      "eyebrow": "02 · Work",
      "title": "Heritage, translated",
      "titleEm": "into form.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "I worked from two fixed sources, one per object. The fork's form is drawn from the client's own traditional Thai architecture; the dessert's silhouette from Korat's old currency. The design decision that held the piece together was pairing them, brand heritage in the tool, civic heritage on the plate, so the two objects read as a matched set rather than a dessert with cutlery beside it. Each source was reduced to a single clean silhouette that had to survive translation into a very different material: one edible and repeatable, one metal and ergonomic."
          ]
        },
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Source",
              "body": "Client's traditional Thai architecture; Korat's historic coinage."
            },
            {
              "num": "02",
              "title": "Translate",
              "body": "Reducing each source to a silhouette that holds as edible form and as cutlery."
            },
            {
              "num": "03",
              "title": "Produce",
              "body": "Prototyping the fork for the hand; setting the dessert form for repeatable service."
            }
          ]
        },
        {
          "type": "image",
          "src": "/projects/signature-dessert-fork/final.png",
          "alt": "The bespoke fork resting beside the plated signature dessert",
          "caption": "Fork drawn from Thai architecture; dessert drawn from Korat's old currency."
        }
      ]
    },
    "outcome": {
      "eyebrow": "03 · Outcome",
      "title": "The result",
      "titleEm": "on the plate.",
      "blocks": [
        {
          "type": "outcomes",
          "items": [
            {
              "value": "2 sources",
              "label": "Heritage languages translated",
              "body": "Client architecture and civic currency rendered into two matched objects."
            },
            {
              "value": "In service",
              "label": "Signature tableware",
              "body": "Both dessert and fork served as the bar's signature pairing after opening."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "Translating fixed heritage, architecture, Korat's currency, into new physical objects is the same move I make now, turning brand and context into a digital product interface."
          ]
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default busabaCaseStudy;
