// Generated by npm run content:flomax — do not edit by hand.
// Edit src/content/case-studies/flomax.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const flomaxCaseStudy = {
  "kind": "minor",
  "slug": "flomax",
  "hero": {
    "breadcrumb": "Flomax",
    "eyebrow": "003 · Graphic Design · Kids mask packaging",
    "titleLine1": "Flomax",
    "titleLine2": "Kids Mask Packaging",
    "summary": "A youths graphic style for Flomax's filter face mask, designed for children while connect to the brand identity.",
    "image": {
      "src": "/projects/flomax/flomax-head-cover.png",
      "alt": "Flomax kids face mask packaging showing the alternative graphic style"
    },
    "meta": [
      {
        "label": "Client",
        "value": "Flomax, air filter manufacturer"
      },
      {
        "label": "Role",
        "value": "Graphic design, packaging design"
      },
      {
        "label": "Timeline",
        "value": "2021"
      },
      {
        "label": "Deliverable",
        "value": "Packaging graphic style for the kids mask"
      }
    ]
  },
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "A new audience,",
      "titleEm": "same brand.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/flomax/flomax-logo.png",
          "alt": "Flomax , an air filters manufactures logo",
          "caption": "Flomax , an air filters manufactures.",
          "size": "md"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  Flomax air filters manufactures had built a facial filter mask line for adults and plan to extend it to a kids product meant the packaging could not simply be scaled down."
          ]
        },
        {
          "type": "image",
          "src": "/projects/flomax/flomax-original-pack.png",
          "alt": "Flomax filter mask original package",
          "caption": "Flomax filter mask original package."
        },
        {
          "type": "prose",
          "paragraphs": [
            "  The original graphics were built to signal filtration performance to an adult buyer, not a child. The constraint was that the new style still had to sit under the same brand identity and shelve beside the adult range as one family. Success meant packaging a child would respond to and a parent would still trust."
          ]
        }
      ]
    },
    "work": {
      "eyebrow": "02 · Work",
      "title": "Playful inside",
      "titleEm": "fixed rules.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/flomax/flomax-original-graphic.png",
          "alt": "Flomax filter mask original packaging elements",
          "caption": "Flomax filter mask original packaging elements."
        },
        {
          "type": "prose",
          "paragraphs": [
            "  I separated the identity's load-bearing elements from the parts open to interpretation, then pushed hard on the open ones. The fixed elements stayed intact so the pack still read as Flomax at a glance, while the flexible layer, illustration, colour handling, and the energy of the layout, carried the shift toward a younger audience."
          ]
        },
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Audit",
              "body": "Separating the adult identity's non-negotiable elements from the flexible ones."
            },
            {
              "num": "02",
              "title": "Shift",
              "body": "Developing a playful register that appeals to children while keeping parental trust."
            },
            {
              "num": "03",
              "title": "Resolve",
              "body": "Holding the pack against the adult range so the two read as one family."
            }
          ]
        },
        {
          "type": "image",
          "src": "/projects/flomax/flomax-comparison-transition.gif",
          "alt": "Graphic elements transition",
          "caption": "Graphic elements transition"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  The balance mattered more than usual here: a mask is only protective if it actually gets worn, so packaging that appeals to a child does real work, but the parent making the purchase still needs the product to read as a filtration product from a manufacturer they trust. The result had to earn attention on a shelf where it sits directly next to its adult counterpart."
          ]
        },
        {
          "type": "image",
          "src": "/projects/flomax/flomax-kid-final.png",
          "alt": "The Flomax kids mask packaging final",
          "caption": "The Flomax kids mask packaging final design."
        }
      ]
    },
    "outcome": {
      "eyebrow": "03 · Outcome",
      "title": "One pack, two",
      "titleEm": "people to convince.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/flomax/flomax-final.png",
          "alt": "The Flomax kids mask packaging shown alongside the adult range",
          "caption": "A register built for children, still recognisably the same filtration brand."
        },
        {
          "type": "outcomes",
          "items": [
            {
              "value": "Two audiences",
              "label": "Child appeal, parent trust",
              "body": "Packaging that speaks to the child wearing the mask and the parent buying it, in one design."
            },
            {
              "value": "Within identity",
              "label": "No rules broken",
              "body": "Tone shifted through the flexible layer while the brand's fixed elements stayed intact."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "  Designing for a user and a buyer who want different things from the same object, without fragmenting the product into two, is a judgement I make constantly in digital product work, where the person using an interface and the person deciding to adopt it are rarely the same."
          ]
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default flomaxCaseStudy;
