// Generated by npm run content:homhuan — do not edit by hand.
// Edit src/content/case-studies/homhuan.md instead.

import type { MajorCaseStudy } from "@/src/lib/case-studies/types";

const homhuanCaseStudy = {
  "kind": "major",
  "slug": "homhuan",
  "hero": {
    "breadcrumb": "Homhuan",
    "eyebrow": "004 · Industrial Design · Heritage Translation · 2019",
    "titleLine1": "Hom",
    "titleLine2": "Huan",
    "summary": "A collection of seven home fragrance products that translate Thai heritage scent practices from a century ago into objects that sit in a modern home without apology.",
    "image": {
      "src": "/projects/homhuan/homhuan-cover.png",
      "alt": "The full Homhuan collection of seven fragrance products arranged as a family"
    },
    "meta": [
      {
        "label": "Role",
        "value": "Solo. Research, concept, industrial design, ceramics and materials, fragrance development, branding and packaging."
      },
      {
        "label": "Team",
        "value": "Solo capstone (industrial design thesis)"
      },
      {
        "label": "Duration",
        "value": "3 months, research through production"
      },
      {
        "label": "Status",
        "value": "Capstone. High Distinction. Exhibited."
      }
    ]
  },
  "sections": {
    "brief": {
      "eyebrow": "01 — Brief",
      "title": "A heritage practice,",
      "titleEm": "made for a modern home",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Home fragrance is bought, used, and refilled endlessly, yet it is almost always culturally anonymous. Meanwhile the Thai heritage scent practices of a century ago survive mostly in period publications, disappearing from use: heritage stays in the museum, and the modern home smells like nowhere in particular.",
            "Homhuan is a collection of seven home-fragrance products, each translated from a different Thai heritage scent practice of a century ago. Every object keeps its source's mechanism or form and updates its use, so a century-old practice can sit in a contemporary space without explaining where it came from."
          ]
        },
        {
          "type": "stats",
          "items": [
            {
              "value": "7",
              "label": "Products",
              "variant": "dark"
            },
            {
              "value": "6",
              "label": "Materials",
              "variant": "mid"
            },
            {
              "value": "5",
              "label": "Signature scents",
              "variant": "mid"
            },
            {
              "value": "3mo",
              "label": "Solo, research to production",
              "variant": "light"
            }
          ]
        }
      ]
    },
    "research": {
      "eyebrow": "02 — Research",
      "title": "A century back,",
      "titleEm": "then forward",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Homhuan started from one object. In an earlier project I had reworked a single Thai heritage candle, **tian ob** — lit, extinguished, and trapped under a lid so its smoke perfumes a dessert — into a modern piece. It translated so cleanly it raised a bigger question: if one heritage practice works this well, what would a whole collection look like?",
            "For the capstone I went back to the source, the golden age of Thai fragrance a century ago, working from period publications rather than modern summaries. Most of what I found described a way of living: how people used scent day to day. That let me translate rituals, not just shapes."
          ]
        },
        {
          "type": "pullquote",
          "text": "One find had no modern record — a fresh-petal recipe I could not source online then, and still cannot today.",
          "source": "Research"
        }
      ]
    },
    "concept": {
      "eyebrow": "03 — Concept",
      "title": "One method,",
      "titleEm": "applied seven times",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Every product followed the same move: take a heritage practice, keep the mechanism or form that made it work, drop its original purpose, and update its use for a modern home. The method stays constant; the source changes seven times."
          ]
        },
        {
          "type": "image",
          "src": "/projects/homhuan/homhuan-translation-matrix.svg",
          "alt": "A matrix showing each of the seven products translated from its heritage source — what was kept, what was dropped, and the resulting modern object — plus one idea cut at the concept stage",
          "caption": "The whole method in one view — seven heritage sources, each stripped to its mechanism and rebuilt as a modern object. The eighth row is the idea I cut."
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Aroma Stove, from the Anglo stove.** The period kitchen's workhorse, kept whole and emptied of its purpose: the heat-and-vessel principle stays, cooking goes, and two vessels split the job of scenting."
          ]
        },
        {
          "type": "imagePair",
          "items": [
            {
              "src": "/projects/homhuan/homhuan-product-brass.png",
              "alt": "Aroma stove configured with a brass pan warming solid incense",
              "caption": "Brass pan over a tea light — dry heat warms solid incense, so scent releases slowly with no flame touching it."
            },
            {
              "src": "/projects/homhuan/homhuan-product-ceramic.png",
              "alt": "Aroma stove configured with a ceramic pot boiling an aroma bag",
              "caption": "Ceramic pot for wet heat — an aroma bag steeps like tea, giving a second, fuller way to run the same stove."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Reed Diffuser, from the Thai floral mobile.** The woven garland was decorative, perishable, and hung. I kept the pattern's structure and swapped what it is made of, so the heritage form never compromises how well it diffuses."
          ]
        },
        {
          "type": "imagePair",
          "items": [
            {
              "src": "/projects/homhuan/homhuan-product-diffuser-inspiration.png",
              "alt": "Traditional Thai floral mobile woven from banana tree and garland",
              "caption": "The source — a flat frame cut from banana tree, woven with a fresh garland, beautiful but wilting within a day."
            },
            {
              "src": "/projects/homhuan/homhuan-product-diffuser.jpg",
              "alt": "Homhuan flat reed diffuser with paper frame and piped fragrance beads",
              "caption": "The translation — paper frame, one unbroken thread, fragrance beads piped where flowers were; a reed-and-oil bottle does the steady work."
            }
          ]
        },
        {
          "type": "pullquote",
          "text": "In the original the flowers were ornament. Here they carry scent.",
          "source": "Reed Diffuser"
        },
        {
          "type": "prose",
          "paragraphs": [
            "**The one I cut — a hanging perfuming candle.** A favourite: rich source, clean translation. It came from scenting a cabinet with a candle, made compact to hang upside down. I cut it anyway. An inverted candle is a safety risk at home, and the collection already scented enclosed spaces elsewhere. It failed twice — as an object you could live with, and as one the set needed."
          ]
        },
        {
          "type": "image",
          "src": "/projects/homhuan/homhuan-dropped-idea.webp",
          "alt": "Concept sketch and render of the rejected upside-down hanging perfuming candle",
          "caption": "Cut at concept stage on two compounding grounds — an inverted flame is unsafe at home, and another product already covered enclosed spaces."
        },
        {
          "type": "pullquote",
          "text": "The method only works if it can reject the ideas you like most.",
          "source": "On curation"
        }
      ]
    },
    "craft": {
      "eyebrow": "04 — Craft",
      "title": "Seven translations,",
      "titleEm": "one period",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Each product translates a different practice from the same era; the diagram above maps all seven at a glance. Two are shown in the concept — here is the full family, with the decision behind each carried in its caption."
          ]
        },
        {
          "type": "imageGrid",
          "items": [
            {
              "src": "/projects/homhuan/homhuan-product-candle.jpg",
              "alt": "Candle with Benjarong-inspired ceramic holder",
              "caption": "Candle, from tian ob. Sized small because the spice-and-wax mix suits tiny batches — which is exactly why refills, not volume, became the model."
            },
            {
              "src": "/projects/homhuan/homhuan-product-hanging-diffuser.png",
              "alt": "Hanging three-dimensional reed diffuser in die-cut paper",
              "caption": "Diffuser, from the mobile again — but read for its silhouette, not its weave, so a single source yields two distinct objects."
            },
            {
              "src": "/projects/homhuan/homhuan-product-container.jpg",
              "alt": "Ceramic perfuming storage desk object",
              "caption": "Perfuming storage, from cabinet scenting. Moved out of the wardrobe onto the desk and given the recovered fresh-petal recipe as its consumable."
            },
            {
              "src": "/projects/homhuan/homhuan-product-miller-locket.jpg",
              "alt": "Ceramic and brass miller for grinding fragrance beads and locket-form solid perfume holder",
              "caption": "Miller keeps the period form but drops the medicinal masher; the locket is paired with it so the make-your-own ritual reads in sequence."
            },
            {
              "src": "/projects/homhuan/homhuan-set.png",
              "alt": "The seven products shown together as a family",
              "caption": "One recurring holder shape, varied only by colour and glaze, lets seven different sources still read as a single family."
            }
          ]
        }
      ]
    },
    "build": {
      "eyebrow": "05 — Build",
      "title": "Making it real,",
      "titleEm": "in three months",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/homhuan/homhuan-render-to-reality.png",
          "alt": "Concept render and shifted collection comparison",
          "caption": "Concept render beside the finished collection — the family held even as individual objects shifted in production."
        },
        {
          "type": "prose",
          "paragraphs": [
            "Homhuan was designed and produced solo in three months across six materials — ceramic, brass, glass, paper, wax, and wood. One holder shape recurs throughout, varied only by colour and glaze, so seven objects still read as one family."
          ]
        },
        {
          "type": "video",
          "src": "/projects/homhuan/homhuan-design-transition-video.mp4",
          "poster": "/projects/homhuan/homhuan-design-transition-poster.png",
          "alt": "Transition from Benjarong porcelain to 3D surface, 2D and CI branding",
          "caption": "Benjarong's raised botanical relief, flattened into a graphic that runs from the holder through the CI and packaging."
        },
        {
          "type": "prose",
          "paragraphs": [
            "The visual language comes from Benjarong porcelain: I flattened its raised botanical relief into a two-dimensional graphic, so the form that shapes the holder also runs through the branding. Each object pairs with its own consumable — seven in all, across five hand-blended signature scents — and the candle was built for refills from the start, so the collection stays in use rather than on a shelf."
          ]
        }
      ]
    },
    "outcome": {
      "eyebrow": "06 — Outcome",
      "title": "What it earned,",
      "titleEm": "and what it taught",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "The panel singled out the five hand-blended scents for balancing Thai and modern character — where traditional Thai aroma is usually overwhelming."
          ]
        },
        {
          "type": "outcomes",
          "items": [
            {
              "value": "High Distinction",
              "label": "Capstone grade",
              "body": "Industrial design thesis"
            },
            {
              "value": "BACC",
              "label": "Degree show",
              "body": "Bangkok Art and Culture Centre"
            },
            {
              "value": "2019",
              "label": "Bangkok Design Week",
              "body": "Selected for exhibition"
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "The translation logic held; the objects did not all resolve. Seven products in three months meant most were built once, not iterated. The stove is the clearest case: the gap between tea light and vessel was too tight, so it overheated, and without airflow holes the flame starved before burning to the end. Both are fixable in a second prototype — neither showed up until the object existed."
          ]
        },
        {
          "type": "reflections",
          "items": [
            "A translation can be conceptually sound and the object still unresolved: concept and object fail in different ways, at different stages.",
            "Killing a flawed idea early is one kind of rigour. Catching what only appears once the thing is real is another.",
            "The standard does not switch off when the concept is approved."
          ]
        }
      ]
    }
  }
} satisfies MajorCaseStudy;

export default homhuanCaseStudy;
