// Generated by npm run content:homhuan — do not edit by hand.
// Edit src/content/case-studies/homhuan.md instead.

import type { MajorCaseStudy } from "@/src/lib/case-studies/types";

const homhuanCaseStudy = {
  "kind": "major",
  "slug": "homhuan",
  "hero": {
    "breadcrumb": "Homhuan",
    "eyebrow": "004 · Industrial Design · Heritage Translation · 2019",
    "titleLine1": "Hom",
    "titleLine2": "Huan",
    "summary": "A collection of seven home fragrance products that translate Thai heritage scent practices from a century ago into objects that sit in a modern home without apology.",
    "image": {
      "src": "/projects/homhuan/homhuan-cover.png",
      "alt": "The full Homhuan collection of seven fragrance products arranged as a family"
    },
    "meta": [
      {
        "label": "Role",
        "value": "Solo. Research, concept, industrial design, ceramics and materials, fragrance development, branding and packaging."
      },
      {
        "label": "Team",
        "value": "Solo capstone (industrial design thesis)"
      },
      {
        "label": "Duration",
        "value": "3 months, research through production"
      },
      {
        "label": "Status",
        "value": "Capstone. High Distinction. Exhibited."
      }
    ]
  },
  "sections": {
    "brief": {
      "eyebrow": "01 — Brief",
      "title": "A heritage practice,",
      "titleEm": "made for a modern home",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Home fragrance is bought, used, and refilled endlessly, yet it is almost always culturally anonymous. Meanwhile the Thai heritage scent practices of a century ago survive mostly in period publications and are disappearing from use. Heritage stays in the museum; the modern home smells like nowhere in particular.",
            "Homhuan is a home fragrance collection of seven products, each translated from a different Thai heritage scent practice of roughly a century ago. Every object keeps its source's mechanism or form and updates its use for a modern home, so a century-old practice can sit in a contemporary space without needing to explain where it came from."
          ]
        },
        {
          "type": "stats",
          "items": [
            {
              "value": "7",
              "label": "Products",
              "variant": "dark"
            },
            {
              "value": "6",
              "label": "Materials",
              "variant": "mid"
            },
            {
              "value": "5",
              "label": "Signature scents",
              "variant": "mid"
            },
            {
              "value": "3mo",
              "label": "Solo, research to production",
              "variant": "light"
            }
          ]
        }
      ]
    },
    "research": {
      "eyebrow": "02 — Research",
      "title": "A century back,",
      "titleEm": "then forward",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Homhuan started from a single object. In an earlier project I had reworked one Thai heritage candle, **tian ob**, lit, extinguished, and trapped under a lid so its smoke perfumes a dessert, into a modern object. It translated so cleanly that it raised a bigger question: if one heritage practice works this well, what would a whole collection look like?",
            "For the capstone I went back to its source, the golden age of Thai heritage fragrance a century ago, working from period publications rather than modern summaries. Most of what I found described a way of living, how people used scent day to day, which let me translate rituals, not just shapes. One find mattered most: a fresh-petal fragrance recipe I could not find online then and still cannot today. That recovered method became the heart of one of the seven products."
          ]
        }
      ]
    },
    "concept": {
      "eyebrow": "03 — Concept",
      "title": "One method,",
      "titleEm": "applied seven times",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Every product followed the same move: take a heritage practice, find the mechanism or form that made it work, keep that, and update its use for a modern home. The method stayed constant while the source changed. Three examples show it working, including the one I cut."
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Aroma Stove, from the Anglo stove.** The Anglo stove was the workhorse of the period home: fuel below, any vessel on top, for boiling and cooking. I kept its operating principle and dropped its purpose. A tea light replaces the fuel, fragrance vessels replace the cookware: a brass pan warms solid incense with dry heat, a ceramic pot boils an aroma bag with wet heat. Nothing about cooking survived. The way it worked did."
          ]
        },
        {
          "type": "imagePair",
          "items": [
            {
              "src": "/projects/homhuan/homhuan-product-brass.png",
              "alt": "Aroma stove configured with a brass pan warming solid incense",
              "caption": "Brass pan, dry heat, solid incense"
            },
            {
              "src": "/projects/homhuan/homhuan-product-ceramic.png",
              "alt": "Aroma stove configured with a ceramic pot boiling an aroma bag",
              "caption": "Ceramic pot, wet heat, aroma bag"
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Reed Diffuser, from the Thai floral mobile.** The traditional mobile is a flat frame cut from banana tree, woven with a fresh garland into a pattern: decorative, perishable, hung. I kept its structure and changed what the pattern is made of. A paper frame replaces the banana tree, a single unbroken thread replaces the garland, and fragrance beads piped along it take the place of the flowers. A reed-and-oil bottle does the steady diffusing, so the heritage form never compromises how well it works."
          ]
        },
        {
          "type": "imagePair",
          "items": [
            {
              "src": "/projects/homhuan/homhuan-product-diffuser-inspiration.png",
              "alt": "Traditional Thai floral mobile woven from banana tree and garland",
              "caption": "The source, a woven floral mobile"
            },
            {
              "src": "/projects/homhuan/homhuan-product-diffuser.jpg",
              "alt": "Homhuan flat reed diffuser with paper frame and piped fragrance beads",
              "caption": "The translation, frame in paper, flowers in scent"
            }
          ]
        },
        {
          "type": "pullquote",
          "text": "In the original the flowers were ornament. Here they carry scent.",
          "source": "Reed Diffuser"
        },
        {
          "type": "prose",
          "paragraphs": [
            "**The one I cut, a hanging perfuming candle.** Not everything survived. It came from perfuming an enclosed cabinet with a candle, made compact to hang upside down in a ceramic holder. It was one of my favourites: rich source, clean translation, new idea. I cut it for two reasons that compounded. An inverted candle, even extinguished, is a real safety risk in a home. And the collection already scented enclosed spaces through another product. It failed the test twice: on whether it survives as a real object someone lives with, and on whether the collection needed it."
          ]
        },
        {
          "type": "image",
          "src": "/projects/homhuan/homhuan-dropped-idea.webp",
          "alt": "Concept sketch and render of the rejected upside-down hanging perfuming candle",
          "caption": "Cut at concept stage, on safety and redundancy"
        },
        {
          "type": "pullquote",
          "text": "The method only works if it can reject the ideas you like most.",
          "source": "On curation"
        }
      ]
    },
    "craft": {
      "eyebrow": "04 — Craft",
      "title": "Seven translations,",
      "titleEm": "one period",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Each product translates a different practice from the same era. The method holds; the source changes seven times. Two are shown above; here is the full set."
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Candle with holder, from tian ob.** A hand-made candle of wax, ground incense and spices, and Thai fragrance oil that scents by smoke. It once perfumed desserts and cloth, so its use was never only food, and I extended that to a room. The holder borrows Benjarong porcelain's form, tying it to the collection's visual language."
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Reed Diffuser in three dimensions, from the mobile's silhouette.** The same object translated again: where the flat version took the mobile's woven structure, this takes its silhouette, die-cut in paper around a central bottle to keep the 360-degree hanging form. One source, two translations."
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Perfuming ceramic storage, from cabinet perfuming.** People once scented cabinets of clothes and accessories with potpourri or smoke candles. I made it a desk object: a ceramic piece holding a house-made gel or potpourri, for accessories, napkins, or the room. The fresh-petal recipe from the research lives here, built into the one product it suited most."
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "**Personal perfume set, the miller and the locket.** Two practices that belong together. The miller comes from mashing fragrance powder beads with perfume and herbs to personal taste; I swapped the medicinal masher for the period's miller form, kept its patterned surface, and preserved the use, so a person can make their own solid perfume."
          ]
        },
        {
          "type": "imageGrid",
          "items": [
            {
              "src": "/projects/homhuan/homhuan-product-candle.jpg",
              "alt": "Candle with Benjarong-inspired ceramic holder",
              "caption": "Candle, from tian ob. Sized small because the spice-wax suits small batches, which made refills the model"
            },
            {
              "src": "/projects/homhuan/homhuan-product-hanging-diffuser.png",
              "alt": "Hanging three-dimensional reed diffuser in die-cut paper",
              "caption": "Diffuser, from the mobile silhouette. Same source, second reading"
            },
            {
              "src": "/projects/homhuan/homhuan-product-container.jpg",
              "alt": "Ceramic perfuming storage desk object",
              "caption": "Perfuming storage, from cabinet scenting. Carries the recovered fresh-petal recipe"
            },
            {
              "src": "/projects/homhuan/homhuan-product-miller-locket.jpg",
              "alt": "Ceramic and brass miller for grinding fragrance beads and Locket-form solid perfume holder",
              "caption": "Miller, from the powder-bead ritual. Period miller form kept, medicinal masher dropped. Locket, from the wax lip locket. Paired with the miller to tell the ritual in sequence"
            },
            {
              "src": "/projects/homhuan/homhuan-set.png",
              "alt": "The seven products shown together as a family",
              "caption": "Seven sources, one collection, one recurring holder shape"
            }
          ]
        }
      ]
    },
    "build": {
      "eyebrow": "05 — Build",
      "title": "Making it real,",
      "titleEm": "in three months",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/homhuan/homhuan-render-to-reality.png",
          "alt": "Concept render and shifted collection comparison",
          "caption": "Concept render and shifted collection comparison"
        },
        {
          "type": "prose",
          "paragraphs": [
            "Homhuan was designed and produced solo in three months, across six materials, including ceramic, brass, glass, paper, wax, wood. One holder shape recurs through the collection, varied by colour and glaze, so seven objects still read as one family."
          ]
        },
        {
          "type": "video",
          "src": "/projects/homhuan/homhuan-design-transition-video.mp4",
          "poster": "/projects/homhuan/homhuan-design-transition-poster.png",
          "alt": "Transition from Benjarong porcelain to 3D surface, 2D and CI branding",
          "caption": "Transition from Benjarong porcelain to 3D surface, 2D and CI branding"
        },
        {
          "type": "prose",
          "paragraphs": [
            "The visual language comes from Benjarong porcelain: I flattened its raised botanical relief into a two-dimensional graphic, so the object that shapes the candle holder also runs through the CI and packaging. Each object is paired with its own consumable fragrance, seven in all, across five hand-blended signature scents. The candle, sized for one or two uses, was built for refills from the start, so the collection stays in use rather than sitting on a shelf."
          ]
        }
      ]
    },
    "outcome": {
      "eyebrow": "06 — Outcome",
      "title": "What it earned,",
      "titleEm": "and what it taught",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "The project earned a High Distinction, went to a review panel, showed at the degree show in the Bangkok Art and Culture Centre, and was selected for Bangkok Design Week 2019. The panel singled out the five hand-blended scents for balancing Thai and modern character, where traditional Thai aroma is usually known for being overwhelming."
          ]
        },
        {
          "type": "outcomes",
          "items": [
            {
              "value": "High Distinction",
              "label": "Capstone grade",
              "body": "Industrial design thesis"
            },
            {
              "value": "BACC",
              "label": "Degree show",
              "body": "Bangkok Art and Culture Centre"
            },
            {
              "value": "2019",
              "label": "Bangkok Design Week",
              "body": "Selected for exhibition"
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "The translation logic held, but the objects were not fully resolved. Seven products in three months meant most were built once, not iterated, and the panel was right that each needed two or three prototype rounds. The stove is the clearest case: the gap between tea light and vessel was too narrow, so the container overheated, and without airflow holes on both sides of the base the flame could not draw enough oxygen to burn to the end. Both are fixable in a second prototype. Neither showed up until the object existed."
          ]
        },
        {
          "type": "reflections",
          "items": [
            "A translation can be conceptually sound and the object still unresolved: concept and object fail in different ways, at different stages.",
            "Killing a flawed idea early is one kind of rigour. Catching what only appears once the thing is real is another.",
            "The standard does not switch off when the concept is approved."
          ]
        }
      ]
    }
  }
} satisfies MajorCaseStudy;

export default homhuanCaseStudy;
