// Generated by npm run content:jtimber — do not edit by hand.
// Edit src/content/case-studies/jtimber.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const jtimberCaseStudy = {
  "kind": "minor",
  "slug": "jtimber",
  "hero": {
    "breadcrumb": "JTimber",
    "eyebrow": "005 · Graphic Design · Flooring catalogue & 3D assets",
    "titleLine1": "JTimber",
    "titleLine2": "Flooring Catalogue",
    "summary": "A 48-page flooring catalogue for a wood styling company, covering all products and services, managing from the assets to coordinated print publication.",
    "image": {
      "src": "/projects/jtimber/jtimber-header.png",
      "alt": "The JTimber flooring catalogue open to a spread showing wood floor colour options"
    },
    "meta": [
      {
        "label": "Client",
        "value": "JTimber, wood flooring & styling company"
      },
      {
        "label": "Role",
        "value": "Graphic design, 3D rendering, retouching, print coordination"
      },
      {
        "label": "Timeline",
        "value": "2023"
      },
      {
        "label": "Deliverable",
        "value": "48-page product catalogue, 3D asset library, print-ready files"
      }
    ]
  },
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "Presenting a brand",
      "titleEm": "on paper.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/jtimber/JTimber-logo.png",
          "alt": "JTimber logo",
          "caption": "JTimber, a wood flooring company logo",
          "size": "md"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  JTimber, a wood flooring company, needed a catalogue to serve as its complete reference document that covering the brand service range, with five content types, each behaving differently on the page. \n  Underneath it all sat one hard constraint: customers choose their floor colour from these pages, so a colour that prints wrong isn't a design flaw—it's a customer receiving a floor they didn't choose."
          ]
        }
      ]
    },
    "work": {
      "eyebrow": "02 · Work",
      "title": "From render to",
      "titleEm": "printed page.",
      "blocks": [
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Structure",
              "body": "Planning an information architecture for the catalogue, considering a user flow."
            },
            {
              "num": "02",
              "title": "Render and Retouch",
              "body": "Generated uniform 3D assets for product variants and calibrated material textures to guarantee print reproduction."
            },
            {
              "num": "03",
              "title": "Publish",
              "body": "Laying out 48 pages across all contents, then coordinating files through an external printer."
            }
          ]
        },
        {
          "type": "image",
          "src": "/projects/bhae/bhaesaj-direction-branding.png",
          "alt": "Mood board for the Bhaesaj modern classic packaging direction",
          "caption": "IA"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  The design necessitated a cohesive and adaptable visual framework to synthesize five distinct content formats into a unified reading experience."
          ]
        },
        {
          "type": "image",
          "src": "/projects/bhae/bhaesaj-direction-branding.png",
          "alt": "Mood board for the Bhaesaj modern classic packaging direction",
          "caption": "Assets creation"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  The assets are built rather than sourcing them, rendering the range in 3D so every colour could be shown in identical lighting and framing, the only way a set of swatches is honestly comparable, and rendering plank cross-sections to turn the engineered build-up into something a customer could grasp at a glance. \n  Retouching resolved what rendering could not, tuning grain and tone so each material read truthfully once printed."
          ]
        },
        {
          "type": "image",
          "src": "/projects/bhae/bhaesaj-direction-branding.png",
          "alt": "Mood board for the Bhaesaj modern classic packaging direction",
          "caption": "Assembly"
        },
        {
          "type": "prose",
          "paragraphs": [
            "  Furthermore, coordination with the external printer required rigorous prepress calibration—specifically regarding colour accuracy, image resolution, and bleed parameters—as post-production modifications are impossible."
          ]
        }
      ]
    },
    "outcome": {
      "eyebrow": "03 · Outcome",
      "title": "A range that",
      "titleEm": "sells itself.",
      "blocks": [
        {
          "type": "image",
          "src": "/projects/timber/final.png",
          "alt": "Spreads from the finished JTimber catalogue showing colour options, laying patterns, and plank construction diagrams",
          "caption": "Product, pattern, and service content unified across forty-eight pages."
        },
        {
          "type": "imageGrid",
          "items": [
            {
              "src": "/projects/quiz-game/quiz-game-identical-platypus.png",
              "alt": "Platypus illustration sample",
              "caption": "imageGrid · item 1",
              "credit": "Credit on grid item",
              "creditHref": "https://example.com"
            },
            {
              "src": "/projects/quiz-game/quiz-game-identical-brolga.png",
              "alt": "Brolga illustration sample",
              "caption": "imageGrid · item 2"
            },
            {
              "src": "/projects/quiz-game/quiz-game-cover.png",
              "alt": "Australia Call cover",
              "caption": "imageGrid · item 3"
            },
            {
              "src": "/projects/quiz-game/quiz-game-identical-platypus.png",
              "alt": "Platypus illustration sample",
              "caption": "imageGrid · item 4",
              "credit": "Credit on grid item",
              "creditHref": "https://example.com"
            },
            {
              "src": "/projects/quiz-game/quiz-game-identical-brolga.png",
              "alt": "Brolga illustration sample",
              "caption": "imageGrid · item 5"
            },
            {
              "src": "/projects/quiz-game/quiz-game-cover.png",
              "alt": "Australia Call cover",
              "caption": "imageGrid · item 5"
            }
          ]
        },
        {
          "type": "outcomes",
          "items": [
            {
              "value": "48 pages",
              "label": "Asset to press",
              "body": "Rendering, retouching, layout, and print coordination handled as a single pipeline."
            },
            {
              "value": "5 contents",
              "label": "One document, covering all jobs",
              "body": "Specifications, colour, patterns, services, and portfolio held together in one visual system."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "Owning something all the way to print, where colour has to be right the first time and every decision is final once the file leaves, built a discipline about shipping that I carry into digital work, even where a fix is always possible."
          ]
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default jtimberCaseStudy;
