// Generated by npm run content:kuendee — do not edit by hand.
// Edit src/content/case-studies/kuendee.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const kuendeeCaseStudy = {
  "kind": "minor",
  "slug": "kuendee",
  "hero": {
    "breadcrumb": "Kuendee",
    "eyebrow": "002 · Booth Design · Modular retail system + graphics",
    "titleLine1": "Kuendee",
    "titleLine2": "Retail Booth",
    "summary": "A reconfigurable retail booth for a fertiliser and gardening materials distributor, splitting a tight footprint into two product zones while displaying as much of a rotating range as possible, with backdrop illustration and infographics designed to match.",
    "image": {
      "src": "/projects/kuendee/cover.png",
      "alt": "Kuendee booth installed in a home improvement store, showing two-sided product display and illustrated backdrop"
    },
    "meta": [
      {
        "label": "Client",
        "value": "Kuendee, fertiliser & gardening materials distributor"
      },
      {
        "label": "Role",
        "value": "Booth design, graphic design, illustration"
      },
      {
        "label": "Timeline",
        "value": "2021"
      },
      {
        "label": "Deliverable",
        "value": "Modular booth system, backdrop illustration, product infographics"
      }
    ]
  },
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "Small footprint,",
      "titleEm": "full range.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Kuendee distributes fertiliser and growing materials, biochar, clay pebbles, and a range that keeps changing, into home improvement, hardware, and outdoor living retailers. The brief set two requirements that pulled against each other. The space was limited and had to be split into two distinct sides: gardening products on one, compost bins and larger goods on the other. At the same time, the display had to carry as much of the range as possible, because a distributor's value to a retailer is showing breadth. Add a product mix that rotates and the client's own expectation that each branch would display a different selection, and a single fixed build would have failed immediately."
          ]
        }
      ]
    },
    "work": {
      "eyebrow": "02 · Work",
      "title": "A system, not",
      "titleEm": "a structure.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "The two requirements only reconcile through density and modularity, so I designed the booth as a set of parts rather than one object, display units that recombine as the range rotates and the footprint changes from retailer to retailer. The split into two zones became the organising logic rather than a limitation: gardening goods read as one coherent story, compost bins and bulk items as another, which let each side be packed tightly without becoming a jumble. Because the products are sacks and loose media rather than clean boxed goods, the units had to carry real weight and present it deliberately. I then designed the graphic layer on top, an illustrated backdrop and a set of product infographics, so a shopper in a hardware aisle could understand what biochar or clay pebbles actually do, and so the identity held together across every configuration."
          ]
        },
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Constraints",
              "body": "A tight two-zone footprint, a rotating range, and heavy, loose-media products."
            },
            {
              "num": "02",
              "title": "Modularise",
              "body": "Rearrangeable display units that maximise range on show and recombine per site."
            },
            {
              "num": "03",
              "title": "Dress",
              "body": "Backdrop illustration and product infographics that explain the range at aisle distance."
            }
          ]
        },
        {
          "type": "image",
          "src": "/projects/kuendee/final.png",
          "alt": "The Kuendee booth configured for a retailer, showing both product zones and the illustrated backdrop",
          "caption": "Two zones, one system, designed to reconfigure per branch while the graphic layer holds the identity constant."
        }
      ]
    },
    "outcome": {
      "eyebrow": "03 · Outcome",
      "title": "Recognisable in",
      "titleEm": "every store.",
      "blocks": [
        {
          "type": "outcomes",
          "items": [
            {
              "value": "2 zones",
              "label": "Split footprint, one identity",
              "body": "Gardening goods and compost bins separated into distinct sides without fracturing the booth's visual language."
            },
            {
              "value": "End to end",
              "label": "Structure to surface",
              "body": "Booth, backdrop illustration, and product infographics designed as a single visual system."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "Designing one system flexible enough to survive every context it lands in, while keeping its identity intact, is exactly the thinking behind a digital design system, where components must hold up across screens and states nobody has drafted yet."
          ]
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default kuendeeCaseStudy;
