// Generated by npm run content:thaihom — do not edit by hand.
// Edit src/content/case-studies/thaihom.md instead.

import type { MinorCaseStudy } from "@/src/lib/case-studies/types";

const thaihomCaseStudy = {
  "kind": "minor",
  "slug": "thaihom",
  "hero": {
    "breadcrumb": "Thai Hom Infographic Book",
    "eyebrow": "011 · Graphic Design · Editorial",
    "titleLine1": "Thai",
    "titleLine2": "Hom",
    "summary": "An infographic book showcasing ingredients that represent Thai aroma, every illustration and graphic element authored by hand for a cohesive sensory narrative.",
    "layout": "split",
    "image": {
      "src": "/projects/thai-hom/thai-hom-cover.png",
      "alt": "Thai Hom cover image"
    },
    "meta": [
      {
        "label": "Client",
        "value": "Concept / academic project"
      },
      {
        "label": "Role",
        "value": "Illustration + graphic design"
      },
      {
        "label": "Timeline",
        "value": "7 weeks"
      },
      {
        "label": "Deliverable",
        "value": "32-page infographic book"
      }
    ]
  },
  "sections": {
    "context": {
      "eyebrow": "01 · Context",
      "title": "Smell is hard",
      "titleEm": "to show.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Thai Hom asks a visual question: how do you communicate aroma without sound or scent? The book maps ingredients, lemongrass, kaffir lime, galangal, jasmine, coconut, and others, that define Thai fragrance culture.",
            "Every spread is original: no stock illustration, no borrowed icons. The goal was a cohesive editorial object where graphic rhythm and hand-drawn detail carry the sensory story."
          ]
        },
        {
          "type": "stats",
          "items": [
            {
              "value": "32",
              "label": "Pages",
              "variant": "dark"
            },
            {
              "value": "18",
              "label": "Ingredient profiles",
              "variant": "mid"
            },
            {
              "value": "100%",
              "label": "Original artwork",
              "variant": "light"
            }
          ]
        }
      ]
    },
    "work": {
      "eyebrow": "02 · Work",
      "title": "Ingredient as",
      "titleEm": "visual character.",
      "blocks": [
        {
          "type": "prose",
          "paragraphs": [
            "Each ingredient received a profile spread: botanical illustration, aroma note diagram, cultural context sidebar, and a graphic pattern derived from the plant's natural geometry. A shared colour system ties herbal, floral, and woody families across the book."
          ]
        },
        {
          "type": "process",
          "items": [
            {
              "num": "01",
              "title": "Research + outline",
              "body": "Eighteen ingredients selected for aroma significance, grouped by scent family."
            },
            {
              "num": "02",
              "title": "Illustration pass",
              "body": "Hand-drawn botanicals digitised with consistent line language and two ink colours."
            },
            {
              "num": "03",
              "title": "Layout + pattern",
              "body": "Grid, typography, and derived geometric patterns built per ingredient chapter."
            }
          ]
        }
      ]
    },
    "outcome": {
      "eyebrow": "03 · Outcome",
      "title": "A book you",
      "titleEm": "can almost smell.",
      "blocks": [
        {
          "type": "outcomes",
          "items": [
            {
              "value": "32",
              "label": "Finished pages",
              "body": "Print-ready PDF with bleed, bound proof produced for academic review."
            },
            {
              "value": "18",
              "label": "Original profiles",
              "body": "Full illustration and infographic treatment per ingredient, no stock assets."
            }
          ]
        },
        {
          "type": "prose",
          "paragraphs": [
            "Thai Hom is the most illustration-heavy piece in my graphic portfolio. Proof that sensory topics reward slow, authored visuals over fast template assembly."
          ]
        }
      ]
    }
  }
} satisfies MinorCaseStudy;

export default thaihomCaseStudy;
